### ISSUE TITLE
Request for additional notes

### ISSUE THREAD

**Issue by ngocanh-dam** [ksgr5566/Google-Data-Analytics#1]
Dear ksgr5566,

I just want to say thank you so much for your notes. It helps me a lot for my learning to get the Google Data Analytic certificate.
I wonder if you can post the notes for the remaining courses of Google Data Analytics ? I will really appreciate it

I look forward to hearing from you,

**Comment by ksgr5566** [comment]
Hey @ngocanh-dam,

I'm truly glad to hear that the notes I posted for the Google Data Analytics course were helpful to you.  It's always inspiring to know that sharing my work can contribute to others' learning journeys.

However, I must admit that I no longer continued with the course and hence stopped making the notes. I'm sure you understand, as we sometimes find our interests shift or evolve.

Given the benefit you've found in the notes, I encourage you to continue where I left off. Not only would it be an excellent learning exercise, but it would also be a valuable contribution to the community. Feel free to fork the repository, add your own notes, and then send a pull request. Your efforts will undoubtedly benefit other learners following the same path.

Best of luck with your studies and future contributions!
